replicaCount: 2



image: 
  repository: nginx
  tag: "1.27.0"
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 80
  anotations: {}

ingress: 
  enabled: false
  className: ""
  anotations: {}
  hosts: {}
  tls: []

resources: {}

httpRoute:
  enabled: false
  hostnames: []
  parentRefs: []
  rules: []

