apiVersion: v1
entries:
  nginx-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-10-16T17:43:23.237071248+05:30"
    description: A Helm chart for Kubernetes
    digest: 8964c46ecef2067a90e52e17f5aea83fcbf1df21da0854e04b1ddac55986c19c
    name: nginx-app
    type: application
    urls:
    - https://deepayan01.github.io/Helm-k8/nginx-app-0.1.0.tgz
    version: 0.1.0
generated: "2025-10-16T17:43:23.236303157+05:30"
