name: defining variable

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
env:
  env_var: "I am a workflow lavel varriable"

jobs:
  echo_job:
    runs-on: ubuntu-latest
    env:
      job_var: "I am a job level var"
    steps:
      - name: printing the variables
        env:
          step_var: "I am a step level var"
        run: |
          echo "print workflow var: ${{ env.env_var }}"
          echo "print job level var: ${{ env.job_var }}"
          echo "print step level var: ${{ env.step_var }}"
  echo_job_2:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: pulling the variable from staging env
        run: |
          echo "staging_var: ${{ TARGET_VAR }}"
  echo_job_3:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: pulling the variable from prod
        run: |
          echo "production_var: ${{ TARGET_VAR_2 }}"
