name: testing context

on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checking the github context
        run: |
          echo "action-repo: ${{ github.repository }}"
          echo "ref: ${{ github.ref }}"
          echo "event: ${{ github.event_name }}"
