name: Expression
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  expression_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking the control flow
        if: ${{ input.debug }}
        run: |
          echo "event: ${{ github.event_name }}"
          echo "ref: ${{ github.ref }}"
