name: functions

on:
  workflow_dispatch:

jobs:
  build_function:
    runs-on: ubuntu-latest
    steps:
      - name: run this job
        run: ls -lrt
      - name: check about the success
        if: ${{ success()}}
        run: echo "the step is successfully executed"
      - name: sleep command
        run: exit 1
      - name: check about failure of previous job
        if: ${{ failure() }}
        run: echo "print job has been failed"
