name: functions

on:
  workflow_dispatch:

jobs:
  build_function:
    runs-on: ubuntu-latest
    steps:
      - name: sleep command
        run: sleep 20
      - name: check about failure of previous job
        if: ${{ failure() }}
        run: echo "print job has been failed"
