name: output-workflow

on:
  workflow_dispatch:
    inputs:
      tags:
        description: tag choices
        type: choice
        options:
          - v1-3.2.7
          - v1.3.2.8
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.new.outputs.tag }}
    steps:
      - id: new
        run: |
          echo "tag=${{ inputs.tags }}" >> "$GITHUB_OUTPUT"
      - name: passing the output value
        run: |
          echo "actual version is ${{ steps.new.outputs.tag }}"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy the particular version
        run: |
          echo "provided version: ${{ needs.build.outputs.version }}"
