# @setup-nodev@3 : install node js on the runner, cache npm, controls node versions per workflow

name: building react application

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - ./docs

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: printing the files
        run: ls -lrt
      - name: set up the node
        uses: actions/setup-node@v3
        with:
          node-version: "24.*"
      - name: install dependencies
        run: npm ci
      - name: running the test
        run: npm run test
#       working-directory: ./react-app
